export default [
  {
    name: "Diabetes",
    eid: "0",
    valuetype: "bool",
    type: "disease",
    defaultValue: "true",
    description:
      "Diabetes is a disease in which your body either can't produce insulin or can't properly use the insulin it produces.",
  },
  {
    name: "Smoker",
    eid: "1",
    valuetype: "bool",
    type: "info",
    defaultValue: "true",
    description: "A person who smokes tobacco regularly.",
  },
  {
    name: "Talker",
    eid: "1",
    valuetype: "bool",
    type: "info",
    defaultValue: "true",
    description: "A person who smokes tobacco regularly.",
  },
  {
    name: "Sleeper",
    eid: "1",
    valuetype: "bool",
    type: "info",
    defaultValue: "true",
    description: "A person who smokes tobacco regularly.",
  },
  {
    name: "Jumper",
    eid: "1",
    valuetype: "bool",
    type: "info",
    defaultValue: "true",
    description: "A person who smokes tobacco regularly.",
  },
  {
    name: "peeper",
    eid: "1",
    valuetype: "bool",
    type: "info",
    defaultValue: "true",
    description: "A person who smokes tobacco regularly.",
  },
  {
    name: "keaper",
    eid: "1",
    valuetype: "bool",
    type: "info",
    defaultValue: "true",
    description: "A person who smokes tobacco regularly.",
  },
  {
    name: "leaper",
    eid: "1",
    valuetype: "bool",
    type: "info",
    defaultValue: "true",
    description: "A person who smokes tobacco regularly.",
  },
  {
    name: "deeper",
    eid: "1",
    valuetype: "bool",
    type: "info",
    defaultValue: "true",
    description: "A person who smokes tobacco regularly.",
  },
];
